#define IDENTIFIER 1
#define CONSTANT 100
#define LEFT_SQUARE_PARENTHESIS 2
#define RIGHT_SQUARE_PARENTHESIS 3
#define LEFT_ROUND_PARENTHESIS 4
#define RIGHT_ROUND_PARENTHESIS 5
#define COLON 6
#define SEMI_COLON 7
#define ASSIGNMENT 8
#define LESS_THAN 9
#define LESS_OR_EQUAL_THAN 10
#define EQUAL 11
#define GREATER_THAN 12
#define GREATER_OR_EQUAL_THAN 13
#define PLUS 14
#define MINUS 15
#define MULTIPLY 16
#define INCREMENT_BY 17
#define DECREMENT_BY 18
#define MULTIPLY_BY 19
#define DIVISION 20
#define MODULO 21
#define COMA 22
#define BOOL 23
#define INT 24
#define STR 25
#define READ 26 
#define WRITE_TO_CONSOLE 27
#define IF 28
#define END_IF 29
#define ELSE 30
#define FOR 31
#define AND 32